In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.3.5'

#Question 2

In [2]:
df=pd.read_csv('master_housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [3]:
#Question 3 Misssing Value

In [4]:
mss_tr=df['total_rooms'].isnull().sum()
print('There are missing Values',mss_tr)

There are missing Values 0


In [5]:
mss_tb=df['total_bedrooms'].isnull().sum()
print('There are missing values here:', mss_tb)


There are missing values here: 207


In [6]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

#Question 4

In [7]:
unique= df['ocean_proximity'].unique()
print(unique)

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


#Question 5

In [8]:
avg= df[
    df['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()
    
print(avg)


259212.31179039303


#Question 6
Calculate the average of total_bedrooms column in the dataset.

In [9]:
avg_tb= df['total_bedrooms'].mean()
print(avg_tb)

537.8705525375618


Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.


In [10]:
df['total_bedrooms'].isnull().sum()

207

In [11]:
df['total_bedrooms'].fillna(avg_tb)
#print(avg_tb)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [12]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [13]:
avg_tb= df['total_bedrooms'].mean()
print(avg_tb)

537.8705525375618


#Question 7
1. Select all the options located on islands
2. Select only columns housing_median_age, total_rooms, total_bedrooms.


In [14]:
X=df[df['ocean_proximity']=='ISLAND']
X=X[['housing_median_age','total_rooms','total_bedrooms']].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [15]:
res_1= X.T@X
print(res_1.shape)
inversa = np.linalg.inv(res_1)
print('It is the inverse\n',inversa)

(3, 3)
It is the inverse
 [[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


Creating vectoy Y

In [26]:
Y=[950, 1300, 800, 1000, 1300]
W= inversa@X.T
w = W@Y
print('The last result is: ',w[-1])

The last result is:  5.699229455065586


Thanks for read this notebook!